build:
  maxIssues: 0
  excludeCorrectable: false

config:
  validation: true
  warningsAsErrors: false
  checkExhaustiveness: false


complexity:
  active: true
  LargeClass:
    active: true
    threshold: 600
  TooManyFunctions:
    active: true
    thresholdInClasses: 30
  NestedBlockDepth:
    active: true
    threshold: 4
  CyclomaticComplexMethod:
    active: true
    threshold: 15

style:
  active: true
  MagicNumber:
    active: true
    ignoreNumbers: ['-1', '0', '1', '2', '3', '4', '5', '6', '8', '10', '12', '16', '24', '30', '32', '48', '50', '60', '64', '100', '128', '255', '256', '500', '1000']
    ignorePropertyDeclaration: true
    ignoreAnnotation: true
    ignoreEnums: true
    ignoreConstantDeclaration: true
  MaxLineLength:
    active: true
    maxLineLength: 300
  ReturnCount:
    active: true
    max: 4
  WildcardImport:
    active: true

exceptions:
  active: true
  TooGenericExceptionCaught:
    active: true
  SwallowedException:
    active: true

empty-blocks:
  active: true
  EmptyFunctionBlock:
    active: true
    ignoreOverridden: true
